# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  - task: YarnInstaller@3
    inputs:
      versionSpec: '1.x'
    displayName: 'Install Yarn'
  - task: CacheBeta@1
    inputs:
      key: yarn2 | $(Agent.OS) | yarn.lock
      path: node_modules
    displayName: Cache node modules
  - script: yarn --frozen-lockfile
    displayName: 'Install dependencies and build'
  - script: |
      yarn test-unit-coverage --forbid-only
      EXIT_CODE=$?
      ./node_modules/.bin/nyc report --reporter=cobertura
      exit $EXIT_CODE
    displayName: 'Unit tests'
  - script: yarn lint
    displayName: 'Lint'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    displayName: 'Publish coverage'

- job: macOS
  pool:
    vmImage: 'macOS-11'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  - task: CacheBeta@1
    inputs:
      key: yarn2 | $(Agent.OS) | yarn.lock
      path: node_modules
    displayName: Cache node modules
  - script: yarn --frozen-lockfile
    displayName: 'Install dependencies and build'
  - script: yarn test-unit --forbid-only
    displayName: 'Unit tests'
  - script: yarn lint
    displayName: 'Lint'

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  - task: CacheBeta@1
    inputs:
      key: yarn2 | $(Agent.OS) | yarn.lock
      path: node_modules
    displayName: Cache node modules
  - script: yarn --frozen-lockfile
    displayName: 'Install dependencies and build'
  - script: yarn test-unit --forbid-only
    displayName: 'Unit tests'
  - script: yarn lint
    displayName: 'Lint'

- job: Linux_IntegrationTests
  pool:
    vmImage: 'ubuntu-20.04'
  container: mcr.microsoft.com/playwright:v1.24.0-focal
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  - task: YarnInstaller@3
    inputs:
      versionSpec: '1.x'
    displayName: 'Install Yarn'
  - script: yarn --frozen-lockfile
    displayName: 'Install dependencies and build'
  - script: npx playwright install
    displayName: 'Install Playwright browsers'
  - script: yarn test-playwright --forbid-only
    displayName: 'Integration tests'

# Integration tests are too flaky on macOS https://github.com/xtermjs/xterm.js/issues/3590
# - job: macOS_IntegrationTests
#   pool:
#     vmImage: 'macOS-10.15'
#   steps:
#   - task: NodeTool@0
#     inputs:
#       versionSpec: '14.x'
#     displayName: 'Install Node.js'
#   - script: yarn --frozen-lockfile
#     displayName: 'Install dependencies and build'
#   - script: yarn test-playwright --forbid-only
#     displayName: 'Integration tests'

- job: Windows_IntegrationTests
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  - script: yarn --frozen-lockfile
    displayName: 'Install dependencies and build'
  - script: npx playwright install
    displayName: 'Install Playwright browsers'
  - script: yarn test-playwright --forbid-only
    displayName: 'Integration tests'

- job: Release
  dependsOn:
  - Linux
  - macOS
  - Windows
  - Linux_IntegrationTests
  # - macOS_IntegrationTests
  - Windows_IntegrationTests
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['FORCE_RELEASE'], 'true')))
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  - task: YarnInstaller@3
    inputs:
      versionSpec: '1.x'
    displayName: 'Install Yarn'
  - task: CacheBeta@1
    inputs:
      key: yarn2 | $(Agent.OS) | yarn.lock
      path: node_modules
    displayName: Cache node modules
  - script: yarn --frozen-lockfile
    displayName: 'Install dependencies and build'
  - script: |
      yarn package-headless
      node ./bin/package_headless.js
    displayName: 'Package xterm-headless'
  - script: NPM_AUTH_TOKEN="$(NPM_AUTH_TOKEN)" node ./bin/publish.js
    displayName: 'Package and publish to npm'
